before_install:
  - sudo apt-get update
  - apt-cache search nvidia
  - sudo apt-get update -qq
  - sudo apt-get install -qq build-essential
  - sudo apt-get install -qq gcc-4.4
  - sudo apt-get install -qq nvidia-common
  - sudo apt-get install -qq nvidia-current
  - sudo apt-get install -qq nvidia-cuda-toolkit nvidia-cuda-dev
  - sudo apt-get install -qq libthrust-dev
  - sudo find /usr/ -name libcuda*.so
  - mkdir libs
  - cd libs
  - curl https://download.libsodium.org/libsodium/releases/libsodium-1.0.11.tar.gz > libsodium-1.0.11.tar.gz
  - tar xvzf libsodium-1.0.11.tar.gz
  - cd libsodium-1.0.11/
  - ./configure
  - make && make check
  - cd ../../

install:
  - make